[package]
name = "clask"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.41", features = ["derive"] }
redis = "0.32.4"
strum = { version = "0.27.2", features = ["derive"] }
